name: Deploy on Push or PR Merge to Staging

on:
  push:
    branches:
      - staging
  pull_request:
    types: [closed]
    branches:
      - staging

jobs:
  deploy:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Executar Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            bash /home/deploy/deploy.sh
            sudo /root/bin/clear.sh

